name: Flutter apk
on: [push]

jobs:
  apk:
    runs-on: ubuntu-latest
    name: Build apk
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      #- name: check vol 4
      #  run: cd /home/runner/work/ && ls
      - name: check vol
        run: cd /home/runner/work/flutter-apk-action/flutter-apk-action && ls
      - name: Setting env and building app
        uses: /home/runner/work/flutter-apk-action/flutter-apk-action/
      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: apk released
          path: './app.apk'
