name: build apk
on:
 push:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
